#! /bin/sh
nitrogen --restore &
xrandr --output DVI-D-0 --mode 1920x1080 --rate 144 &
sxhkd &
killall -q polybar

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

# Launch Polybar, using default config location ~/.config/polybar/config
polybar bar &

bspc monitor -d I II III IV V VI VII VIII IX X
bspc config top_padding         20
bspc config border_width         6
bspc config window_gap          10

bspc config split_ratio          0.60
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
# source the colors.


# Set the border colors.
bspc config normal_border_color '#665c54'
bspc config active_border_color '#fe8019'
bspc config focused_border_color '#fe8019'
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color '#689d6a'
